version: '3'

services:
  client:
  # restart: always # NOTE: use with caution, restarts service when it crashes
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
  api:
  # restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    #depends_on: #depends on databases
    #  - serviceName
    volumes:
      - ./api:/app